#+PAGETITLE: EAEE TA Resources
#+STARTUP:    showall
#+AUTHOR: Adam Massmann
#+EMAIL: akm2203 "at" columbia "dot" edu
#+LANGUAGE: en

** EAEE TA Documentation: Help out the next TA generation (which could be you!)

   This is the website for a [[https://ctl.columbia.edu/][CTL]]-sponsored workshop on documenting TA
   course materials and adding them to a repository for future TAs'
   use. The workshop is hosted in an asynchronous/synchronous format
   (details below). Participants will learn first hand about
   documenting course materials by contributing to a repository of
   EAEE documentation.

   After the workshop is over, I will modify this website to become a
   landing page for future TAs' use. Basically, when TAs get their TA
   assignment for the semester, they will gain permission to view and
   benefit from their course's repository containing all past
   materials. At the end of the semester, the new TA will add their
   notes and contributions from the course, so future TAs will get the
   same benefit. This type of community effort and repository will
   save department TAs a ton of time in the long run: it may take a
   little time to document your course contributions at the end of the
   semester, but it will save you a bunch of time next year when you
   benefit from others' work.

** Instructions

   1. Read through this webpage. Send any questions to Adam (uni:
      akm2203).
   2. If you plan on attending the synchronous zoom meeting (details
      below), please fill out your availability in the [[https://www.when2meet.com/?8962735-fjLcS][when2meet]] so we
      can schedule a time that works for the most people.
   3. *Required for TAs*: Add your name, contact information, and time
      spent TAing to the course repositories corresponding to any
      courses you TA'd in the past (or currently, but in that case try
      and base the time spent on pre-COVID-19 conditions in
      Jan/Feb). Each course repository is available further down on
      this page, and an example document is [[https://docs.google.com/document/d/1fV2Ux1FamerTGpWi74t8r1GnPfnO4aJpjhDLFEwLVhA/edit?usp=sharing][here]]. If there is no
      repository for a course you TA'd for, or you do not have
      permissions to edit, email Adam (uni: akm2203) and he will fix
      it.
   4. Additionally, upload any course materials or documentation you
      have to your course repository's folder. Ideas and descriptions
      for materials and documentation are under the section
      "/Materials to Document/" on this webpage. More is better when
      it comes to documentation and please remember that the expected
      amount you get out of any community effort is proportional to
      the amount you put in.
   5. If you came across any frequently asked questions from students
      during your course and you documented the answers, add these to
      the Student FAQ Google Doc in your course respository. An
      example is also [[https://docs.google.com/document/d/1tU4cYfTnPPxTATnUdLqaK5Z69cOEnaHKGZXop56H-AQ/edit?usp=sharing][here]].
   6. *Required for non-TAs, recommended for all*: If you have never
      been a TA, you can still participate! Add your contact
      information to the [[https://docs.google.com/document/d/1G9RP-Xpefz0XbgiVjvUEUR8BPmGeOqkGRgEAM-SHsbk/edit?usp=sharing][EAEE-PhD-Student-Resources]] Google Doc, and
      optionally update the document with any resources or information
      you think will be helpful to new EAEE students (that may or may
      not be TAs). You can also upload any other materials that do not
      fit within the document format to the resources [[https://drive.google.com/drive/folders/16vFLRhV8zds_UYv3W_SXswAD45no8QEu?usp=sharing][folder]].
   7. Attend the synchronous zoom session on *Tuesday, April 14th at
      2:30 p.m.* We will discuss and improve the process for sharing
      course materials and documents, and put together a plan for the
      future. This will be a very informal meeting, so is also a
      chance for us to see each other and catch up with all of the
      chaos that has been going on!

** Workshop Objectives for Participants

   - Understand how organization and documentation can collectively
     save all EAEE TAs time: there is a lot of repeat work (e.g.,
     generating solutions) that can be avoided year to year. Also
     within a given year, organization and documentation strategies
     can save you time. For example, formal grading rubrics can help
     the grading process, mediate grading disagreements with students,
     and improve course consistency year-to-year.
   - Apply revisions to improve course materials: revising problem
     sets, solutions, and frequently asked questions/answers can
     remove major time sinks for future TAs. In particular, ambiguous
     problems should be removed through revision; these are a main
     pain point for many TAs during grading, office hours, and student
     questions.
   - Awareness of available tools for communal documentation, and
     their strengths and weaknesses.


** Possible Materials to Document

    - *TA responsibilities and weekly time spent on each
      responsibility (on average)*. The department does not tell TAs
      how much time they will spend on a course. Documenting how much
      time you spent (on average) as a TA is a way for future TAs to
      get an idea of how much time they will spend, so they can plan
      accordingly. Documenting responsibilities is a very simple and
      minimal piece of documentation that can be very helpful for
      future TAs.
    - *Solutions to problem sets and exams*, and any other answer
      keys. Many TAs needlessly repeat work by generating the same set
      of solutions as previous years' TAs.
    - *Student FAQ (and answers)*. Many students ask the same
      questions; documenting the answers to those questions can save
      future TAs the time needed to re-craft the same answers. Also
      through iteration we can improve the answers to frequently asked
      questions year after year.
    - *Revised problem sets and lab activities*. Consider revising
      problem sets again /after/ grading for the benefit of next
      year's TAs. For example, if an ambiguous question created issues
      during grading, revise the question to be less ambiguous and post
      it to the respository.
    - *Grading rubrics*. Grading rubrics make the grading process more
      efficient, help mediate grading disagreements with students, and
      improve course consistency year-to-year. Creating grading
      rubrics can save you time, and adding them to the course
      repository can save future TAs time.
    - *Learning Objectives*. Learning objectives are what you hope
      students will gain from a course, lesson, or problem set. There
      is a whole course design philosophy called "backwards design"
      where the teacher defines the learning objectives first, and
      then designs every element of the course in service of meeting
      the learning objectives. Documenting learning objectives can help
      future TAs design course elements and assignments. For more on
      learning objectives, I recommend the CTL's [[https://www.columbia.edu/content/events/essentials-teaching-and-learning-backward-design-and-learning-objectives-graduate-students][Workshop on Backwards
      Design and Learning Objectives]]. They usually offer it every
      semester.
    - *Course notes, lecture slides and syllabus.* Self explanatory,
      but documenting can save future TAs time, and improve the quality
      of the course through iterative refinement.

** Contributing Guidelines

   For file uploads to the Google Drive folder in your course
   respository, please add a dated prefix to the filename of the form
   "YYYY-Semester-filename.extension." Please *do not include any
   spaces* in the filename. For example, if I was uploading a picture
   of the first midterm solutions for Fall of 2019 I would call the
   file:

   "2019-Fall-midterm1-solutions.jpg"

   Or if I was uploading a pdf of the first Problem Set for a course
   in Spring of 2020, I would call the file:

   "2020-Spring-ps1.pdf"

   Please reach out to Adam (uni: akm2203) if you have any questions.

** Repository Tools

   Initially I set up the repository to be hosted on Google Drive with
   help from Google Doc, etc. The benefits of this approach are:

   - All Columbia affiliates have Google Suites associate with their
     uni's. This makes access and managing permissions easier.
   - Can restrict access to only certain people (e.g. people who are
     or have been TAs for the course - very important for keeping
     solutions private).
   - Low barrier to entry (most people know how to use already, or can
     learn quickly how to use the Google Suite).

   Disadvantages:

   - ethics of using Google, a large corporation dealing in consumer
     advertising and surveillance.

   There are other possible repositories for hosting websites. These
   include:

   - Dropbox
   - Gihub (or Gitlab, bitbucket)
   - Custom website (e.g. Github hosted)

   We can discuss advantages and disadvantages of repository hosting
   software and organization strategies in the synchronous zoom
   meeting. We can use our initial experience with Google Drive to
   modify and change the approach to organization and hosting going
   forwards.

** Course Repositories

*** CO2 utilization and conversion (EAEE 4305)

    - [[https://drive.google.com/open?id=1wy4oES-408RcYdSvSz4VhjOu-fkFMNqYf9gtvOEb1ac][Previous TAs and Course Responsibilities]] : (required) put your
      contact information, the responsibilities you had as a TA, and
      the average weekly amount of time you spent on each
      responsibility (I know this varies strongly week to week, but
      just put an estimate on average time per week). Below the
      tables, you can optionally also add any other information you
      would like future TAs to know.
    - [[https://drive.google.com/open?id=1578uzHSKhynHof7jA2jHL5WDlhu7CEOtCf8VDFO_cLg][Student FAQ (with answers)]] : (optional) if you came across any
      common questions students asked, put them here and write down
      what your response/answer was so future TAs can use that as a
      starting point.
    - [[https://drive.google.com/open?id=1-AbF9c7RAztb23mGdEZHKnhxmHr2hUOo][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document.

*** A better planet by design (EAEE 2100)
    - [[https://drive.google.com/open?id=1mnbYxHmjbuJ9Q9dFDtCwPqL0E13eKfSB2Oqo1n-ZN_M][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=1SydPr-8aGv7yWH8_pORgBy7NEbdRmEW1eWaLyE2MJCk][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-F1mqv_3tHMB1BrRr87n97wVkPLi1Lk8][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document.

*** Alternative energy resources (EAEE 2002/4002)

    - [[https://drive.google.com/open?id=1KN5rX5QtdD6X0wnOl1UdIsN9ONUY6-LrYsrm4YE96l0][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=1XyJs8pQDFKt2LCZxH6w1sBpOmDJJAWyRswz4czhkR18][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-QCpkvvXDYp1kiVEevhWiCk3VERvwh9r][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document.


*** Applied transport and chemical rate phenomena (EAEE 3200)
    - [[https://drive.google.com/open?id=1R_q9IyA4hpos7zQK_x2NR3xvbFEtzCNyMVfxFRXefj4][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=1ZFU4oCMxvvBdLDR8xfCGb3WXWQ5fgLb3XV5zkV4nyg0][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-cJfQj-fjiO2c6fB5XZQSg0CQFKyX8Dr][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document.



*** Physical hydrology (EAEE 6240)

    - [[https://drive.google.com/open?id=18KP7fvxV7enSepjLTd8T7jqN372Jyn_4hJMEF8mfFkM][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=1yuP8ciY1Yf7d4Dk-3A5W4T6nL_P7RMD-xUg_YTyFLf8][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-dxMpt9gi9O1ncRdDb7sJI0kBDItsazD][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document.


*** Environmental data analysis & modeling (EAEE 4257)

    - [[https://drive.google.com/open?id=1miM06ZoTv62FFneJi284l6mnZ9X4J1JQT_PiULpNXqY][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=12Ro_I_a4dT8BK9ZaO7tsR5xGYNwM4pVNUcJooJKLFEc][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-g1hactELHuoyW8sJ6KuDvA8rKPGBFIT][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document


*** Management and development of water systems (ECIA 4100)


    - [[https://drive.google.com/open?id=1IVNMaff-i_Pvf73GNS56JBC4OjgIfDQ5GlJYdPoSj3Q][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=1DheMnyN0vecx4-IMCDEJArUvRZ3seMartu9gXjQv2sc][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-j9Q59b86aj5EmmCnX0rGXgUqpsTa3G9][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document


*** Industrial ecology of earth resources (EAEE 4001)

    - [[https://drive.google.com/open?id=1VyjE1CQfFeiWGpePn8n-lcaGOP9otZSIpE92EcVrGBQ][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=14uIpoNFZI_x0CfWWPOvLhSSUjyxNm97s8z1-_vBpuXg][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-pasBhpfQCUvNNZ4JTqUcEay2A1gt8fJ][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document

*** Industrial ecology of manufacturing (EAEE 4011)
    - [[https://drive.google.com/open?id=1Wg5-m8oR-0uQ81IVri8-fDOzK7HsGjtWVkKGq9_xI4Y][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=14-KpyXTDdCum0WfgoT3FcTSNtIR7gtc01oOQLesUxFM][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=1-wQSEycsrSuw9bpl_oK7X2is0nqlxQ-a][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document

*** Energy, Minerals, Materials Systems (EAEE 3103)

    - [[https://drive.google.com/open?id=1mM4CV6z65v_-ABgVrC7vAuqPWxDE0MpS5w09cl_LIws][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=1JLRt-38rzarxED3yuudaZmlR0GYEga7SNRwCL6XISRk][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=10DCXKEHvSzdiPjg_tSPCh0T4SLSamjgd][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document


*** Industrial catalysis (EAEE 6150)


    - [[https://drive.google.com/open?id=1K5oN2QkXqia9rB0Nd7pWQ9w9ciPJEqAUbBsS0gL-T6I][Previous TAs and Course Responsibilities]] : (required) put your contact
      information, the responsibilities you had as a TA, and the
      average weekly amount of time you spent on each responsibility
      (I know this varies strongly week to week, but just put an
      estimate on average time per week). Below the tables, you can
      optionally also add any other information you would like future TAs to
      know.
    - [[https://drive.google.com/open?id=1EY5j6pdRKbTStP9txoPNJ2S0C0fazHCRtQfphbYYnQs][Student FAQ (with answers)]] : (optional) if you came across any common
      questions students asked, put them here and write down what your
      response/answer was so future TAs can use that as a starting point.
    - [[https://drive.google.com/open?id=10GjfbQws28SlhnkvAkT1Z4KT_i-LpVTN][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document

** General EAEE Graduate Student resources (not TA-specific)

   - [[https://drive.google.com/open?id=1G9RP-Xpefz0XbgiVjvUEUR8BPmGeOqkGRgEAM-SHsbk][EAEE-PhD-Student-Resources]] - put your contact information, as
     well as anything you think would be useful for new EAEE Ph.D. students.
   - [[https://drive.google.com/open?id=16vFLRhV8zds_UYv3W_SXswAD45no8QEu][EAEE Ph.D. Resource Folder]] - upload any materials that are useful
     for new EAEE Ph.D. students that do not fit into the above Google
     Doc.

** Contact

   Please contact Adam Massmann (akm2203) with any questions,
   concerns, and/or issues.

** This workshop, the CTL and the LTF program

   This workshop is sponsored by the [[https://ctl.columbia.edu/][Center for Teaching and
   Learning]]'s (CTL) [[https://ctl.columbia.edu/graduate-instructors/opportunities-for-graduate-students/lead-teaching-fellows/][Lead Teaching Fellowship]] (LTF). LTFs receive a
   stipend of $1000 per a semester to attend 3 pedagogy workshops for
   professional personal development, host their own pedagogy related
   workshop, and liaison between academic departments and the CTL. The
   CTL also offers a bunch of programming to help graduate students
   and instructors; see their website for more details. A good
   starting point is also the [[https://ctl.columbia.edu/graduate-instructors/programs-for-graduate-students/ctl-teaching-development-program/][Teaching Development Program]].
