#+PAGETITLE: EAEE TA Resources
#+STARTUP:    showall
#+AUTHOR: Adam Massmann
#+EMAIL: akm2203 "at" columbia "dot" edu
#+LANGUAGE: en

** EAEE Graduate Student and TA Documentation Repository

   This website hosts documentation for EAEE graduate students and
   TAs. The website if provided for EAEE students, by EAEE students,
   and was originally put together by the participants of a [[https://ctl.columbia.edu/][Center for
   Teaching and Learning]]-sponsored workshop. The original workshop
   website is available at
   http://www.columbia.edu/~akm2203/eaee-ta-resources-workshop-version.html
   if you want more information.

   Please browse the website for links to general documentation for
   graduate student and TAs, as well as course-specific documentation
   for TAs. To protect materials, course-specific documentation has
   restricted permissions to those that are currently or have
   previously been TAs of the course. If you cannot access materials
   that you should have permission for, just email Adam (uni: akm2203)
   and he will fix it.

** General EAEE Graduate Student resources (not TA-specific)

   - [[https://drive.google.com/open?id=1G9RP-Xpefz0XbgiVjvUEUR8BPmGeOqkGRgEAM-SHsbk][EAEE-PhD-Student-Resources]] - put your contact information, as
     well as anything you think would be useful for new EAEE Ph.D. students.
   - [[https://drive.google.com/open?id=16vFLRhV8zds_UYv3W_SXswAD45no8QEu][EAEE Ph.D. Resource Folder]] - upload any materials that are useful
     for new EAEE Ph.D. students that do not fit into the above Google
     Doc.

** General EAEE TA resources (not course-specific)
   - [[https://drive.google.com/open?id=11CtnP6b9XiIIkwqhN-H3P8evJnZzAOfNNfc6MnvpOmk][EAEE General TA Resources]] - document of general ideas and
     resources for TAs.
   - [[https://drive.google.com/open?id=11zI63C5Vvl85B4pWQBX0SRVLIgYsPb0J][EAEE General TA Folder]] - a place to upload any stand alone
     documents or materials.

** Repository TO-DO list

   - Think of a catchy name for these resources. "EAEE Graduate
     Student and TA Documentation Repository" isn't drawing anyone in!
   - Outreach to include new Ph.D.-track students and TAs at EAEE
     orientation. This might require creating a separate Ph.D.-track
     only orientation that does not yet exist. During the workshop we
     discussed just a really short (~1 hr) student-run orientation
     where we introduce things like this repository, and more
     generally just being a graduate student in the department. Sara
     (thanks Sara!)  volunteered to reach out to the department about
     how we might do this (Thanos?), and Adam is also available to
     help/facilitate the orientation.
   - (at some point) Pass this repository on when Adam graduates. Ian
     volunteered to take it over (thanks Ian!).

** Contributing guidelines for course-specific materials

   For file uploads to the Google Drive folder in course-specific
   repositories, please add a dated prefix to the filename of the
   form "YYYY-Semester-filename.extension." Please *do not include any
   spaces* in the filename. For example, if I was uploading a picture
   of the first midterm solutions for Fall of 2019 I would call the
   file:

   "2019-Fall-midterm1-solutions.jpg"

   Or if I was uploading a pdf of the first Problem Set for a course
   in Spring of 2020, I would call the file:

   "2020-Spring-ps1.pdf"

   Please reach out to Adam (uni: akm2203) if you have any questions.

   If you already have a course repository hosted on another platform
   like Github or Dropbox, you can continue to host the repository on
   that platform. Just add a Google document to the Google drive
   folder with a link to the external repository and instructions for
   how to obtain access/edit permissions.

*** Ideas of course-specific materials to Document

    - *Contact information*
    - *TA responsibilities and weekly time spent
      on each responsibility (on average)*. The department does not
      tell TAs how much time they will spend on a course. Documenting
      how much time you spent (on average) as a TA is a way for future
      TAs to get an idea of how much time they will spend, so they can
      plan accordingly.
    - *Solutions to problem sets and exams*, and any other answer
      keys. Many TAs needlessly repeat work by generating the same set
      of solutions as previous years' TAs.
    - *Grading rubrics*. Grading rubrics make the grading process more
      efficient, help mediate grading disagreements with students, and
      improve course consistency year-to-year. Creating grading
      rubrics can save you time, and adding them to the course
      repository can save future TAs time.
    - *Learning Objectives*. Learning objectives are what you hope
      students will gain from a course, lesson, or problem
      set. Defining learning objectives before making assessments and
      lessons can help make sure course elements are working in
      service of the learning objectives (this is called "backwards
      design").
    - *Revised problem sets and lab activities*. Consider revising
      problem sets again /after/ grading for the benefit of next
      year's TAs. For example, if an ambiguous question created issues
      during grading, revise the question to be less ambiguous and post
      it to the repository.
    - *Course notes, lecture slides and syllabus.* Self explanatory,
      but documenting can save future TAs time, and improve the quality
      of the course through iterative refinement.
    - *Student FAQ (and answers)*. Many students ask the same
      questions; documenting the answers to those questions can save
      future TAs the time needed to re-craft the same answers. Also
      through iteration we can improve the answers to frequently asked
      questions year after year.
    - *Course specific recommended boundaries.* Setting clear
      boundaries is important for the mental health of both TAs and
      students. Providing a list of boundaries that made the course
      run smoother can help future TAs' courses run smoother (e.g.,
      only ask questions over Piazza instead of email, only answer
      questions during certain times of the day like 9-5, etc.).
    - *Recommendations for successfully working with/for course
      professors*. Every person is different and has their own
      management and organization styles. As we work with someone
      through the semester, we learn the best way to work with them
      given their style. Documenting how you improved your working
      relationship can help future TAs successfully work with faculty.

** Course-specific Repositories

*** CO2 utilization and conversion (EAEE 4305)

    - [[https://drive.google.com/open?id=1wy4oES-408RcYdSvSz4VhjOu-fkFMNqYf9gtvOEb1ac][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1578uzHSKhynHof7jA2jHL5WDlhu7CEOtCf8VDFO_cLg][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-AbF9c7RAztb23mGdEZHKnhxmHr2hUOo][Folder for uploading other course materials]] : folder for any
      other course materials (see ideas section above).

*** A better planet by design (EAEE 2100)
    - [[https://drive.google.com/open?id=1mnbYxHmjbuJ9Q9dFDtCwPqL0E13eKfSB2Oqo1n-ZN_M][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1SydPr-8aGv7yWH8_pORgBy7NEbdRmEW1eWaLyE2MJCk][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-F1mqv_3tHMB1BrRr87n97wVkPLi1Lk8][Folder for uploading other course materials]] : folder for any
      other course materials (see ideas section above).

*** Alternative energy resources (EAEE 2002/4002)

    - [[https://drive.google.com/open?id=1KN5rX5QtdD6X0wnOl1UdIsN9ONUY6-LrYsrm4YE96l0][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1XyJs8pQDFKt2LCZxH6w1sBpOmDJJAWyRswz4czhkR18][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-QCpkvvXDYp1kiVEevhWiCk3VERvwh9r][Folder for uploading other course materials]] : folder for any
      other course materials (see ideas section above).

*** Environmental data analysis & modeling (EAEE 4257)

    - [[https://drive.google.com/open?id=1miM06ZoTv62FFneJi284l6mnZ9X4J1JQT_PiULpNXqY][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=12Ro_I_a4dT8BK9ZaO7tsR5xGYNwM4pVNUcJooJKLFEc][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-g1hactELHuoyW8sJ6KuDvA8rKPGBFIT][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document

*** Energy, Minerals, Materials Systems (EAEE 3103)

    - [[https://drive.google.com/open?id=1mM4CV6z65v_-ABgVrC7vAuqPWxDE0MpS5w09cl_LIws][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1JLRt-38rzarxED3yuudaZmlR0GYEga7SNRwCL6XISRk][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=10DCXKEHvSzdiPjg_tSPCh0T4SLSamjgd][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document


*** Management and development of water systems (ECIA 4100)

    - [[https://drive.google.com/open?id=1IVNMaff-i_Pvf73GNS56JBC4OjgIfDQ5GlJYdPoSj3Q][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1DheMnyN0vecx4-IMCDEJArUvRZ3seMartu9gXjQv2sc][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-j9Q59b86aj5EmmCnX0rGXgUqpsTa3G9][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document


*** Industrial ecology of earth resources (EAEE 4001)

    - [[https://drive.google.com/open?id=1VyjE1CQfFeiWGpePn8n-lcaGOP9otZSIpE92EcVrGBQ][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=14uIpoNFZI_x0CfWWPOvLhSSUjyxNm97s8z1-_vBpuXg][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-pasBhpfQCUvNNZ4JTqUcEay2A1gt8fJ][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document

*** Industrial ecology of manufacturing (EAEE 4011)
    - [[https://drive.google.com/open?id=1Wg5-m8oR-0uQ81IVri8-fDOzK7HsGjtWVkKGq9_xI4Y][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=14-KpyXTDdCum0WfgoT3FcTSNtIR7gtc01oOQLesUxFM][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-wQSEycsrSuw9bpl_oK7X2is0nqlxQ-a][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document

*** Industrial catalysis (EAEE 6150)

    - [[https://drive.google.com/open?id=1K5oN2QkXqia9rB0Nd7pWQ9w9ciPJEqAUbBsS0gL-T6I][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1EY5j6pdRKbTStP9txoPNJ2S0C0fazHCRtQfphbYYnQs][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=10GjfbQws28SlhnkvAkT1Z4KT_i-LpVTN][Folder for uploading other course materials]] : (optional) upload
      any other course materials here. See the "/Materials to
      Document/" section above for ideas of what to document

*** Physical hydrology (EAEE 6240)

    - [[https://drive.google.com/open?id=18KP7fvxV7enSepjLTd8T7jqN372Jyn_4hJMEF8mfFkM][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1yuP8ciY1Yf7d4Dk-3A5W4T6nL_P7RMD-xUg_YTyFLf8][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-dxMpt9gi9O1ncRdDb7sJI0kBDItsazD][Folder for uploading other course materials]] : folder for any
      other course materials (see ideas section above).


*** Applied transport and chemical rate phenomena (EAEE 3200)
    - [[https://drive.google.com/open?id=1R_q9IyA4hpos7zQK_x2NR3xvbFEtzCNyMVfxFRXefj4][Previous TAs and Course Responsibilities]] : a document with
      contact information, TA responsibilities, the average weekly
      amount of time spent on each responsibility (I know this varies
      strongly week to week, but these are just an estimate on average
      time per week), and any other information that might help future
      TAs (see ideas section above).
    - [[https://drive.google.com/open?id=1ZFU4oCMxvvBdLDR8xfCGb3WXWQ5fgLb3XV5zkV4nyg0][Student FAQ (with answers)]] : any common questions students ask,
      with previous TAs' responses. Future TAs can then use these
      answers as a starting point, and edit, improve, and add to them
      as needed.
    - [[https://drive.google.com/open?id=1-cJfQj-fjiO2c6fB5XZQSg0CQFKyX8Dr][Folder for uploading other course materials]] : folder for any
      other course materials (see ideas section above).

** Contact

   Please contact Adam Massmann (akm2203) with any questions,
   concerns, and/or issues.
