#+STARTUP:    showall
#+PAGETITLE:      Adam's mesoscale meteorology research

*** Master's Projects at UAlbany (mesoscale meteorology)

**** Lake-effect Snow

     While at UAlbany I focused on using numerical experiments to improve
     our understanding of lake-effect snowstorms (LES). LES occur when cold
     air crossing the relatively warm waters of the Great Lakes generate
     powerful storms under synoptic conditions usually associated with fair
     weather. A newsworthy example of this phenomenon was the [[http://www.weather.gov/buf/lake1415_stormb.html][Buffalo]]
     snowstorm of Nov. 17-21, 2014 that dropped up to 2 meters of snow and
     shut down the city.

     Under the advisement of [[http://www.atmos.albany.edu/facstaff/jminder/][Dr. Justin Minder]], I created a semi-idealized
     modeling framework for studying LES. This involved stripping all
     unnecessary model complexities while still preserving the necessary
     dynamics to resolve LES. Simplified initial and boundary conditions
     allowed me to manipulate model state space in a controlled manner and
     test specific hypotheses.

     I made a poster explaining initial lake-effect snow results for the
     [[https://www2.ametsoc.org/ams/index.cfm/meetings-events/ams-meetings/16th-conference-on-mesoscale-processes/][16th Conference on Mesoscale Processes]]. Poster available [[file:docs/Massmann_Mesoscale.pdf][here]].

**** Orographic Rain

     A secondary research interest was orographically enhanced rain in
     coastal mountain ranges. From 5/17/2015 - 8/24/2015 I was in Chile
     conducting an exploratory field campaign (Chilean Coastal Orographic
     Precipitation Experiment pilot project, CCOPE-15) in the Nahuelbuta
     Mountains to the south of Concepci\oacute{}n. UAlbany collaborated with
     researchers at the University of Colorado, University of Wyoming,
     Universidad de Chile, and Universidad de Concepci\oacute{}n to observe the
     kinematic and microphysical aspects of landfalling storms.

     *Links*

      - [[http://www.atmos.albany.edu/student/massmann/ccope.html][Field project website]]
      - [[https://ams.confex.com/ams/17Mountain/webprogram/Paper296523.html][Presentation at 17th Conference on Mountain Meteorology]]
      - [[https://journals.ametsoc.org/doi/full/10.1175/JHM-D-17-0005.1][Paper on the project]]
