#+STARTUP: showall
#+PAGETITLE: Writing resources

** Writing resources

   Writing is always a struggle for me. I am trying to get better, and
   here are some resources that help:

   - [[http://www.cis.upenn.edu/~sweirich/icfp-plmw15/slides/peyton-jones.pdf]["How to write a great research paper" by Simon Peyton-Jones]].
     Biggest takeaway for me: writing is a method for *doing research*
     rather than just *communicating research*. Start writing right
     away (just a research idea is usually enough to start on an
     introduction). I really wish I came across this earlier in my
     Ph.D... A video of the presentation is also [[https://www.microsoft.com/en-us/research/academic-program/write-great-research-paper/][hosted by
     Microsoft.]]
   - [[http://www.cs.cmu.edu/~pausch/Randy/Randy/raibert.htm]["Good Writing" by Marc Raibert]] : general advice on how to become a
     good writer.
   - "Furor Scribendi" by Octavia Butler : advice for aspiring writers
     that resonates for amateurs too. Echos ideas from Marc Raibert
     above (e.g. good writing starts bad), but also discusses the
     importance of habit and persistence. "Furor Scribendi" is under
     copyright, but it is published as part of the anthology
     "[[https://en.wikipedia.org/wiki/Bloodchild_and_Other_Stories][Bloodchild and Other Stories]]" which can be picked up at most
     libraries.
   - [[http://www.ccs.neu.edu/home/shivers/diss-advice.html]["Dissertation Advice" by Olin Shivers]] : specific to dissertations
   - George Orwell's 6 rules:
     1. Never use a metaphor, simile, or other figure of speech which
        you are used to seeing in print.
     2. Never use a long word where a short one will do.
     3. If it is possible to cut a word out, always cut it out.
     4. Never use the passive where you can use the active.
     5. Never use a foreign phrase, a scientific word, or a jargon
        word if you can think of an everyday English equivalent.
     6. Break any of these rules sooner than say anything outright
        barbarous.
   - [[https://twitter.com/sapinker/status/1084490338629242880][Steven Pinker's 13 rules on twitter]], reproduced here:
     1. Reverse-engineer what you read. If it feels like good writing,
        what makes it good? If it’s awful, why?
     2. Prose is a window onto the world. Let your readers see what you are seeing by using visual, concrete language.
     3. Don’t go meta. Minimize concepts about concepts, like "approach, assumption, concept, condition, context, framework,
        issue, level, model, perspective, process, range, role, strategy, tendency," and "variable."
     4. Let verbs be verbs. Appear," not "make an appearance."
     5. Beware of the Curse of Knowledge: when you know something,
        it’s hard to imagine what it’s like not to know it. Minimize
        acronyms & technical terms. Use "for example" liberally. Show
        a draft around, & prepare to learn that what’s obvious to you
        may not be obvious to anyone else.
     6. Omit needless words (Will Strunk was right about this).
     7. Avoid clichés like the plague (thanks, William Safire).
     8. Old information at the beginning of the sentence, new information at the end.
     9. Save the heaviest for last: a complex phrase should go at the
        end of the sentence.
     10. Prose must cohere: readers must know how each sentence is
         related to the preceding one. If it’s not obvious, use "that
         is, for example, in general, on the other hand, nevertheless,
         as a result, because, nonetheless," or "despite."
     11. Revise several times with the single goal of improving the prose.
     12. Read it aloud.
     13. Find the best word, which is not always the fanciest
         word. Consult a dictionary with usage notes, and a thesaurus.
   - Many universities have writing centers ([[https://www.college.columbia.edu/core/uwp/writing-center][including Columbia]]) that
     host office hours and consultations: get help from professionals!
